
public interface MedioDePago {
	void abonarOperacion(float valor);
}


enum TipoMedio {
	CREDIT_CARD, DEBIT_CARD, CASH, ATM, ACCOUNT_MONEY;
}

enum IDMedioDePago{
	VISA, MASTER, AMEX, DINERS, NARANJA, NATIVA, SHOPPING, 
	CENCOSUD, CMR_MASTER, ARGENCARD,CORDIAL,CORDOBESA,CABAL,
	DEB_VISA, DEB_MASTER, MAESTRO, DEB_CABAL, PAGOFACIL, 
	RAPIPAGO, BAPROPAGOS, CARGAVIRTUAL, COBROEXPRESS,REDLINK,
	ACCOUNT_MONEY; 
}