package paymentMethods;

public enum IDMedioDePago{
	VISA, MASTER, AMEX, DINERS, NARANJA, NATIVA, SHOPPING, 
	CENCOSUD, CMR_MASTER, ARGENCARD,CORDIAL,CORDOBESA,CABAL,
	DEB_VISA, DEB_MASTER, MAESTRO, DEB_CABAL, PAGOFACIL, 
	RAPIPAGO, BAPROPAGOS, CARGAVIRTUAL, COBROEXPRESS,REDLINK,
	ACCOUNT_MONEY; 
}